name: Review PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  review_pr_title:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Check PR title format
        id: check_title
        run: |
          TITLE='${{ github.event.pull_request.title }}'
          if [[ ! "$TITLE" =~ ^(feat|fix|docs|chore|perf|test|refactor): ]]; then
            echo "::error::PR title does not follow the convention 'type: description'. Please review the title."
            gh pr review ${{ github.event.pull_request.number }} -r -b "This PR does not satisfies PR title format. Title format should be same as one of the conventional commits"
            exit 1
          else
            echo "PR title meets the required format."
          fi
            